Load Balancer Simulation: LoadBalancer Class Reference
LoadBalancer Class Reference
A load balancer that distributes requests across multiple servers.
#include <load_balancer.h>
Public Member Functions
LoadBalancer (size_t runtime, size_t num_servers, size_t num_requests)
Construct a new Load Balancer.
void run (ostream &os=std::cout)
Run the load balancer simulation.
void printLog (ostream &os=std::cout) const
Print the simulation results and statistics.
Private Member Functions
size_t random (size_t min, size_t max)
Generate a random number between min and max inclusive.
string generateIP ()
Generate a random IP address string.
void generateRequests (size_t num_requests, ostream *os=nullptr)
Generate a specified number of random requests.
void createServers (size_t num_servers)
Initialize the server pool with a specified number of servers.
void assignRequest (Server &server)
Assign a pending request to a specific server.
Private Attributes
size_t runtime
Total simulation runtime in seconds.
size_t clock
Current simulation time.
size_t max_servers
Maximum number of servers allowed.
vector< Server > servers
Pool of available servers.
vector< tuple< Request, Server, size_t > > handled
Log of handled requests with completion times.
queue< Request > requests
Queue of pending requests.
Detailed Description
A load balancer that distributes requests across multiple servers.
The LoadBalancer class manages a pool of servers and distributes incoming requests among them using a simple round-robin algorithm. It simulates network traffic by generating random requests and assigning them to available servers.
Definition at line 30 of file load_balancer.h.
Constructor & Destructor Documentation
LoadBalancer()
LoadBalancer::LoadBalancer (size_t runtime, size_t num_servers, size_t num_requests)
Construct a new Load Balancer.
Parameters
runtime Total simulation runtime in seconds
num_servers Number of servers to initialize
num_requests Number of requests to generate
Definition at line 3 of file load_balancer.cpp.
References clock, createServers(), generateRequests(), max_servers, and runtime.
Member Function Documentation
assignRequest()
void LoadBalancer::assignRequest (Server & server) private
Assign a pending request to a specific server.
Parameters
server Reference to the server that will handle the request
Definition at line 46 of file load_balancer.cpp.
References requests, and Server::setRequest().
Referenced by run().
createServers()
void LoadBalancer::createServers (size_t num_servers) private
Initialize the server pool with a specified number of servers.
Parameters
num_servers Number of servers to create
Definition at line 40 of file load_balancer.cpp.
References servers.
Referenced by LoadBalancer().
generateIP()
string LoadBalancer::generateIP () private
Generate a random IP address string.
Returns
Random IP address in format "xxx.xxx.xxx.xxx"
Definition at line 16 of file load_balancer.cpp.
References random().
Referenced by generateRequests().
generateRequests()
void LoadBalancer::generateRequests (size_t num_requests, ostream * os = nullptr) private
Generate a specified number of random requests.
Parameters
num_requests Number of requests to generate
os Optional output stream for logging
Definition at line 24 of file load_balancer.cpp.
References generateIP(), random(), and requests.
Referenced by LoadBalancer(), and run().
printLog()
void LoadBalancer::printLog (ostream & os = std::cout) const
Print the simulation results and statistics.
Parameters
os Output stream for logging (defaults to std::cout)
Definition at line 103 of file load_balancer.cpp.
References handled, requests, runtime, and servers.
random()
size_t LoadBalancer::random (size_t min, size_t max) private
Generate a random number between min and max inclusive.
Parameters
min Minimum value
max Maximum value
Returns
Random number between min and max
Definition at line 12 of file load_balancer.cpp.
Referenced by generateIP(), generateRequests(), and run().
run()
void LoadBalancer::run (ostream & os = std::cout)
Run the load balancer simulation.
Parameters
os Output stream for logging (defaults to std::cout)
Definition at line 51 of file load_balancer.cpp.
References assignRequest(), clock, generateRequests(), handled, max_servers, random(), requests, runtime, and servers.
Member Data Documentation
clock
size_t LoadBalancer::clock private
Current simulation time.
Definition at line 33 of file load_balancer.h.
Referenced by LoadBalancer(), and run().
handled
vector<tuple<Request, Server, size_t> > LoadBalancer::handled private
Log of handled requests with completion times.
Definition at line 36 of file load_balancer.h.
Referenced by printLog(), and run().
max_servers
size_t LoadBalancer::max_servers private
Maximum number of servers allowed.
Definition at line 34 of file load_balancer.h.
Referenced by LoadBalancer(), and run().
requests
queue<Request> LoadBalancer::requests private
Queue of pending requests.
Definition at line 37 of file load_balancer.h.
Referenced by assignRequest(), generateRequests(), printLog(), and run().
runtime
size_t LoadBalancer::runtime private
Total simulation runtime in seconds.
Definition at line 32 of file load_balancer.h.
Referenced by LoadBalancer(), printLog(), and run().
servers
vector<Server> LoadBalancer::servers private
Pool of available servers.
Definition at line 35 of file load_balancer.h.
Referenced by createServers(), printLog(), and run().
The documentation for this class was generated from the following files:
load_balancer.h
load_balancer.cpp